<?php
    include "./configuracion/sistema.php";
    $VECTOR_DE_DATOS[ 'NOMBRE_DEL_SISTEMA_C'     ] = $NOMBRE_DEL_SISTEMA;
    $VECTOR_DE_DATOS[ 'AUTOR_DEL_SISTEMA_C'      ] = $AUTOR_DEL_SISTEMA;
    $VECTOR_DE_DATOS[ 'USUARIO_ADMINISTRADOR_C'  ] = $USUARIO_ADMINISTRADOR;
    $VECTOR_DE_DATOS[ 'CLAVE_DE_ADMINISTRADOR_C' ] = $CLAVE_DE_ADMINISTRADOR;
?>